### ISSUE TITLE
build failing in openshift lab scenarios

### ISSUE THREAD

**Issue by luqmanbarry** [openshift-katacoda/blog-django-py#12]
$ oc status
------ Output  ----
In project myproject on server https://openshift:6443

svc/blog-django-py - 10.217.5.217:8080
  deployment/blog-django-py deploys istag/blog-django-py:latest <-
    bc/blog-django-py source builds https://github.com/openshift-katacoda/blog-django-py on openshift/python:latest 
      build #1 failed 1 second ago - 35b89e2: Update package versions. (Graham Dumpleton <Graham.Dumpleton@gmail.com>)
    deployment #1 running for about a minute - 0/1 pods growing to 1

Errors:
  * build/blog-django-py-1 has failed.

1 error, 1 info identified, use 'oc status --suggest' to see details.

**Comment by luqmanbarry** [comment]
Hey, seem like a version problem in the requirements.txt file for the dependency psycopg2. Changing the version solved the problem (2.8.6 in my case).

**Comment by ryanj** [comment]
Thanks for reporting - this should be fixed.
